routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::middleware(['role:Master'])->resource('users',\App\Http\Controllers\UserController::class);

//Worker Page
Route::middleware(['role:Master|Worker'])->get("/worker", function () {
    return View::make("worker");
})->name('worker-page');

//Agency Page
Route::middleware(['role:Master|Agency'])->get("/agency", function () {
    return View::make("agency");
})->name('agency-page');

//Manager Page
Route::middleware(['role:Master|Manager'])->get("/manager", function () {
    return View::make("manager");
})->name('manager-page');

app/Models/Organization.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Organization extends Model
{
    use HasFactory;
    protected $guarded=[];
    protected $table='organizations';
    public function users()
    {
        return $this->belongsToMany(User::class, 'user_organizations', 'organization_id', 'user_id');
    }

}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'role_id',
        'email',
        'password',
        'avatar',
        'surname',
        'phone_no',
        'address1',
        'address2',
        'town',
        'postcode',
        'fire_marshall',
        'first_aid',
        'enabled',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function organizations()
    {
        return $this->belongsToMany(Organization::class, 'user_organizations','user_id','organization_id');
    }
}

app/Models/UserOrganization.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class UserOrganization extends Model
{
    use HasFactory;
    protected $guarded=[];
    var $table = 'user_organizations';

    function user() {
        return $this->belongsTo(User::class);
    }

    function organization() {
        return$this->belongsTo(Organization::class);
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $user=Auth::user();
        return view('home');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Spatie\Permission\Models\Permission;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth']);
//        $this->middleware(['role:Super-Admin|Document Admin'],['except' => ['index']]);
        $this->middleware(['role:Master'],['only' => ['index']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $query=User::query();
        if (isset($request->email))
        {
            $query->where('email','like',"%$request->email%");
        }
        if (isset($request->role_id))
        {
            $query->whereRoleId($request->role_id);
        }
        $users=$query->get();
        return view('users.list',compact('users','request'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required',
            'password' => 'required',
            'email' => 'required|unique:users|max:255',
            'phone_no' => 'required',

//            'image' => 'mimes:jpeg,jpg,png,gif|required|max:2048'
        ]);
        $img = $request->image;
        $folderPath = "user_avatars/";
        $image_parts = explode(";base64,", $img);
        $image_type_aux = explode("image/", $image_parts[0]);
        $image_type = $image_type_aux[1];
        $image_base64 = base64_decode($image_parts[1]);
        $fileName = uniqid() . '.'.$image_type;
        $file = $folderPath . $fileName;
        Storage::disk('public')->put($file, $image_base64);
        $data=$request->except('image','_token','password','permissions','organizations','enabled','fire_marshall','first_aid','role_id');
        if (isset($request->first_aid)){
            $data['first_aid']=1;
        }if (isset($request->first_aid)){
            $data['enabled']=1;
        }if (isset($request->first_aid)){
            $data['fire_marshall']=1;
        }

        $data['avatar']=$folderPath . $fileName;
        $data['password']=Hash::make($request->password);
        $user=User::create($data);
        $user->assignRole($request->role_id);
        if (isset($request->permissions))
        {
            $permissions=$request->permissions;
            foreach ($permissions as $p) {
                $permission=Permission::findById($p);
                $user->givePermissionTo($permission);
            }
        }
        if (isset($request->organizations))
        {
            $organizations=$request->organizations;
            foreach ($organizations as $o) {
                $user->organizations()->attach($o);
            }
        }
        alert('Success','User Created Successfully','success');
        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user=User::find($id);
        $user->delete();
        alert('Deleted','User Deleted','danger');
        return redirect()->route('users.index');
    }
}

resources/views/users/create.blade.php
<!--  Extra Large modal example -->
<div class="modal fade bs-example-modal-xl" tabindex="-1" role="dialog" aria-labelledby="addUserModal"
     aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addUserModal">Add User Form</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-7">
                        <form action="{{route('users.store')}}" method="post" enctype="multipart/form-data">
                            @csrf
                            <div class="row">
                                <div class="col-md-6">
                                    <div id="my_camera" style="width: 200px !important;"></div>
                                    <br/>
                                    <input type=button value="Take Snapshot" onClick="take_snapshot()">
                                    <input type="hidden" name="image" class="image-tag">
                                </div>
                                <div class="col-md-6">
                                    <div id="results">Your captured image will appear here...</div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <div class="mb-3">
                                            <label class="form-label" for="formrow-Fullname-input">Name</label>
                                            <input type="text" class="form-control" id="formrow-Fullname-input"
                                                   placeholder="Name" name="name" required>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <div class="mb-3">
                                            <label class="form-label">Surname</label>
                                            <input type="text" class="form-control"
                                                   placeholder="Surname" name="surname" required>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label class="form-label"
                                               for="formrow-email-input">Email</label>
                                        <input type="email" class="form-control"
                                               id="formrow-email-input" name="email"
                                               placeholder="Email address" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label class="form-label"
                                               for="formrow-password-input">Password</label>
                                        <input type="password" name="password" class="form-control"
                                               id="formrow-password-input"
                                               placeholder="Password" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label class="form-label"
                                               for="formrow-email-input">Mobile</label>
                                        <input type="text" class="form-control"
                                               id="formrow-email-input" name="phone_no"
                                               placeholder="Mobile" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label class="form-label"
                                               for="formrow-password-input">Role</label>
                                        <select name="role_id" id="" class="form-control" required>
                                            <option value="" disabled readonly>Select Role</option>
                                            @foreach(\Spatie\Permission\Models\Role::all() as $role)
                                                <option value="{{$role->id}}">{{$role->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label class="form-label"
                                               for="formrow-email-input">Address 1</label>
                                        <input type="text" class="form-control"
                                               id="formrow-email-input" name="address1"
                                               placeholder="Address 1" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label class="form-label"
                                               for="formrow-email-input">Address 2</label>
                                        <input type="text" class="form-control"
                                               name="address2"
                                               placeholder="Address 2" required>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label class="form-label"
                                               for="formrow-email-input">Town</label>
                                        <input type="text" class="form-control"
                                               name="town"
                                               placeholder="Town" required>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label class="form-label"
                                               for="formrow-email-input">Post Code</label>
                                        <input type="text" class="form-control"
                                               name="postcode"
                                               placeholder="Post Code" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="mb-3">
                                        <div class="form-check form-switch form-switch-md">
                                            <input type="checkbox" name="enabled" class="form-check-input" >
                                            <label class="form-check-label" >Enabled</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="mb-3">
                                        <div class="form-check form-switch form-switch-md">
                                            <input type="checkbox" class="form-check-input"
                                                   id="fire_marshall-customCheck" name="fire_marshall" checked>
                                            <label class="form-check-label" for="formrow-customCheck">Fire Marshall</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="mb-3">
                                        <div class="form-check form-switch form-switch-md">
                                            <input type="checkbox" class="form-check-input"
                                                   id="first_aid-customCheck" name="first_aid" checked>
                                            <label class="form-check-label" for="formrow-customCheck">First Aid</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="mb-3">
                                        <label class="form-label"
                                               for="formrow-email-input">Organizations</label>
                                        <select name="organizations[]" class="select2 form-control select2-multiple" multiple="multiple" data-placeholder="Choose ...">
                                            @foreach(\App\Models\Organization::all() as $organization)
                                                <option value="{{$organization->id}}">{{$organization->name}}</option>
                                            @endforeach
                                        </select>

                                    </div>
                                </div>
                            </div>

                            <div class="d-flex flex-wrap gap-3 mt-3">
                                <button type="submit"
                                        class="btn btn-primary waves-effect waves-light w-md">Submit
                                </button>
                                <button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-4">
                        <h4 class="mb-0">Permissions</h4>
                        @foreach(\Spatie\Permission\Models\Permission::all() as $permission)
                            <div class="col-md-12">
                                <div class="mb-3">
                                    <label class="form-label">{{$permission->name}}</label>
                                    <div class="form-check">
                                        <input type="checkbox" class="form-check-input"
                                               id="{{$permission->name}}-customCheck" name="permissions[]">
                                        <label class="form-check-label"
                                               for="{{$permission->name}}-customCheck">Yes</label>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

resources/views/users/list.blade.php
@extends('layouts.app')

@section('content')
    <!-- select2 css -->
    <link href="{{asset('assets/libs/select2/css/select2.min.css')}}" rel="stylesheet" type="text/css"/>

    <div class="page-content">
        <div class="container-fluid">
            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box d-flex align-items-center justify-content-between">
                        <h4 class="mb-0">Users</h4>
                        <div class="page-title-right">
                            <ol class="breadcrumb m-0">
                                <li class="breadcrumb-item"><a href="javascript: void(0);">Users</a></li>
                                <li class="breadcrumb-item active">List</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end page title -->
            @include('users.search')
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            @if(count($errors)>0)
                                @foreach ($errors->all() as $error)
                                    <p class="alert alert-danger">{{ $error }}</p>
                                @endforeach
                            @endif
                            <h2 class="card-title">Users List</h2>
                            <!-- Extra Large modal -->
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <a class="btn btn-success waves-effect waves-light" data-bs-toggle="modal"
                                       data-bs-target=".bs-example-modal-xl"><i class="mdi mdi-plus me-2"></i> Add
                                        New</a>
                                </div>
                            </div>
                            @include('users.create')
                            <table id="datatable-buttons"
                                   class="table "
                                   style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                                <thead>
                                <tr>
                                    <th></th>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Mobile</th>
                                    <th>Role</th>
                                    <th>Status</th>
                                    <th>Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse($users as $user)
                                    <tr>
                                        <td><input type="checkbox" name="user_checkbox[]" class="user_checkbox" value="{{$user->id}}" /></td>
                                        <td>{{$user->id}}</td>
                                        <td>
                                            @if(!is_null($user->avatar))
                                                <img src="{{url('storage/'.$user->avatar)}}" alt=""
                                                     class="avatar-xs rounded-circle me-2">
                                            @else
                                                <div class="avatar-xs d-inline-block me-2">
                                                    <div
                                                        class="avatar-title bg-soft-primary rounded-circle text-primary">
                                                        <i class="mdi mdi-account-circle m-0"></i>
                                                    </div>
                                                </div>
                                            @endif
                                            <a href="#" class="text-body">{{$user->name}}</a>
                                        </td>
                                        <td>{{$user->email}}</td>
                                        <td>{{$user->phone_no}}</td>
                                        <td>{{$user->roles->pluck('name')[0]}}</td>
                                        <td>
                                            @if($user->enabled==1)
                                                <span class="btn btn-success ">Yes</span>
                                            @else
                                                <span class="btn btn-danger ">No</span>
                                            @endif

                                            {{$user->status}}</td>
                                        <td>
                                            <ul class="list-inline mb-0">
{{--                                                <li class="list-inline-item">--}}
{{--                                                    <a href="javascript:void(0);" class="px-2 text-primary"><i--}}
{{--                                                            class="uil uil-pen font-size-18"></i></a>--}}
{{--                                                </li>--}}
                                                <li class="list-inline-item">
                                                    <form action="{{route('users.destroy',$user->id)}}" method="post">
                                                        {{ method_field('delete') }}
                                                        @csrf
                                                        <button class="px-2 text-danger"
                                                                onclick="return confirm('Are you sure?');"
                                                                type="submit"><i
                                                                class="uil uil-trash-alt font-size-18"></i></button>

                                                    </form>
                                                </li>
                                                {{--                                                <li class="list-inline-item dropdown">--}}
                                                {{--                                                    <a class="text-muted dropdown-toggle font-size-18 px-2" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true">--}}
                                                {{--                                                        <i class="uil uil-ellipsis-v"></i>--}}
                                                {{--                                                    </a>--}}

                                                {{--                                                    <div class="dropdown-menu dropdown-menu-end">--}}
                                                {{--                                                        <a class="dropdown-item" href="#">Action</a>--}}
                                                {{--                                                        <a class="dropdown-item" href="#">Another action</a>--}}
                                                {{--                                                        <a class="dropdown-item" href="#">Something else here</a>--}}
                                                {{--                                                    </div>--}}
                                                {{--                                                </li>--}}
                                            </ul>
                                        </td>
                                    </tr>
                                @empty
                                @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div> <!-- end col -->
            </div> <!-- end row -->

        </div> <!-- container-fluid -->
    </div>
@endsection
@section('custom_scripts')
    <!-- Required datatable js -->
    <script src="{{asset('assets/libs/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{asset('assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{asset('assets/libs/datatables.net-select-bs4/js/select.bootstrap4.min.js')}}"></script>
    <!-- Buttons examples -->
    <script src="{{asset('assets/libs/datatables.net-buttons/js/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('assets/libs/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js')}}"></script>
    <script src="{{asset('assets/libs/jszip/jszip.min.js')}}"></script>
    <script src="{{asset('assets/libs/pdfmake/build/pdfmake.min.js')}}"></script>
    <script src="{{asset('assets/libs/pdfmake/build/vfs_fonts.js')}}"></script>
    <script src="{{asset('assets/libs/datatables.net-buttons/js/buttons.html5.min.js')}}"></script>
    <script src="{{asset('assets/libs/datatables.net-buttons/js/buttons.print.min.js')}}"></script>
    <script src="{{asset('assets/libs/datatables.net-buttons/js/buttons.colVis.min.js')}}"></script>

    <!-- Responsive examples -->
    <script src="{{asset('assets/libs/datatables.net-responsive/js/dataTables.responsive.min.js')}}"></script>
    <script src="{{asset('assets/libs/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js')}}"></script>
    <!-- select 2 plugin -->
    <script src="{{asset('assets/libs/select2/js/select2.min.js')}}"></script>
    <!-- Datatable init js -->
    <script src="{{asset('assets/js/pages/datatables.init.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/webcamjs/1.0.25/webcam.min.js"></script>
    <script language="JavaScript">
        Webcam.set({
            width: 240,
            height: 120,
            image_format: 'jpg',
            jpeg_quality: 100
        });
        Webcam.attach('#my_camera');

        function take_snapshot() {
            Webcam.snap(function (data_uri) {
                $(".image-tag").val(data_uri);
                document.getElementById('results').innerHTML = '<img src="' + data_uri + '"/>';
            });
        }

        // Select2
        $(".select2").select2(
            {
                dropdownParent: $('#addUserModal'),
                width: '100%'
            }
        );

    </script>
@endsection